[tools]
codex = "latest"
gemini = "latest"
node = "lts"
opencode = "latest"
uv = "latest"
"npm:@github/copilot" = "latest"
wrangler = "latest"
"npm:ccusage" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node", "perl"]
